### ISSUE TITLE
lua-protobuf 使用请教

### ISSUE THREAD

**Issue by JieTrancender** [sniper00/BallGame#1]
新项目使用protobuf3所以不能使用云大的pbc了，转移到lua-protobuf了之后遇到了内存没释放的问题。
当前我们是每个agent都各自load pb数据，但是agent退出后cmem固定大小内存没有释放，追踪下来是pb数据导致的。
看了这个项目是按下面共享的方式使用，请问线上有跑吗？稳定不。
https://github.com/sniper00/BallGame/blob/3ca46f0a7ee89a2d45bf23241cff6fa1cf31002a/server/main.lua#L28-L42

**Comment by sniper00** [comment]
我们线上是这样用的，没有遇到问题。 需要注意的是：
1.  **加载.pb数据的这个服务生命周期要和整个进程保持一致**。
2.  **pb一般在进程启动时就加载**
3.  为了方便多luaVM使用 我对lua-protobuf代码有些改动 增加了`pb.share_state() `，你可以直接拷贝我目录地代码来使用

**Comment by JieTrancender** [comment]
1.了解，并且在所有agent使用前加载。
2. 我直接clone你的lua-protobuf编译就可以了对吧

**Comment by sniper00** [comment]
> 1.了解，并且在所有agent使用前加载。 2. 我直接clone你的lua-protobuf编译就可以了对吧

嗯，可以

**Comment by JieTrancender** [comment]
非常感谢解答。

**Comment by sanergogogo** [comment]
pb不需要在每个agent都去加载吧(或者说不需要在agent里面处理pb的解析)，在socket.start之前加载一次。然后每次收到网络消息先解析好数据，再发送给相应agent的处理

**Comment by sniper00** [comment]
> pb不需要在每个agent都去加载吧(或者说不需要在agent里面处理pb的解析)，在socket.start之前加载一次。然后每次收到网络消息先解析好数据，再发送给相应agent的处理

这个看设计，你说的方案多了一次编码解码消耗。 并且在agent上处理，可以多线程分摊编码解码cpu消耗。

**Comment by sanergogogo** [comment]
> > pb不需要在每个agent都去加载吧(或者说不需要在agent里面处理pb的解析)，在socket.start之前加载一次。然后每次收到网络消息先解析好数据，再发送给相应agent的处理
> 
> 这个看设计，你说的方案多了一次编码解码消耗。 并且在agent上处理，可以多线程分摊编码解码cpu消耗。

这个确实是，看需求了
