### ISSUE TITLE
大佬，帮忙看一下，demo无法运行

### ISSUE THREAD

**Issue by liyqxtu** [sniper00/BallGame#3]
# moon\moon.exe main_hub.lua 10000 node.json
2023-04-09 16:58:49.285 | 3484      | INFO  | INIT with 4 workers.
2023-04-09 16:58:49.286 | 3536      | INFO  | WORKER-1 START
2023-04-09 16:58:49.289 | 3456      | INFO  | WORKER-2 START
2023-04-09 16:58:49.290 | 5100      | INFO  | WORKER-3 START
2023-04-09 16:58:49.291 | :01000001 | INFO  | [WORKER 1] new service [bootstrap]
2023-04-09 16:58:49.291 | 5672      | INFO  | WORKER-4 START
2023-04-09 16:59:01.668 | 3536      | ERROR | new_service lua_error:
moon/lualib/moon.lua:111: moon/lualib/moon.lua:186: bad argument #3 to '_newservice' (table expected, got no value)
stack traceback:
        [C]: in upvalue '_newservice'
        moon/lualib/moon.lua:186: in function 'moon.new_service'
        main_hub.lua:74: in local 'fn'
        moon/lualib/moon.lua:254: in upvalue 'invoke'
        moon/lualib/moon.lua:261: in function <moon/lualib/moon.lua:259>
stack traceback:
        [C]: in function 'error'
        moon/lualib/moon.lua:111: in upvalue 'coresume'
        moon/lualib/moon.lua:288: in function 'moon.async'
        main_hub.lua:67: in main chunk
        [C]: in ?. (lua_service.cpp:134)
2023-04-09 16:59:01.668 | :01000001 | INFO  | [WORKER 1] destroy service [bootstrap]
2023-04-09 16:59:01.683 | 5672      | INFO  | WORKER-4 STOP
2023-04-09 16:59:01.684 | 5100      | INFO  | WORKER-3 STOP
2023-04-09 16:59:01.685 | 3456      | INFO  | WORKER-2 STOP
2023-04-09 16:59:01.685 | 3536      | INFO  | WORKER-1 STOP
2023-04-09 16:59:01.686 | 3484      | INFO  | STOP

**Comment by liyqxtu** [comment]
local services = {
    {
        unique = true,
        name = "cluster",
        file = "moon/service/cluster.lua",
        threadid = 1,
        etc_host = serverconf.NODE_ETC_HOST,
        etc_path = "/conf.cluster"
    }
}
查了一下，conf.cluster 找不到，不知道是不是缺少这个文件引起的

**Comment by sniper00** [comment]
> 

你是用最新代码编译的吗？

**Comment by liyqxtu** [comment]
我的电脑上没有vs2022，只有vs2015，无法编译moon，所以在moon仓库也提了一个issue，希望大佬能兼容一下vs2015,。
这个测试的moon.exe是在moon仓库的release页面下载的windows版本

**Comment by liyqxtu** [comment]
自己尝试将c++17的语法改成传统的c++语法，很多地方编译报错，很多模板的写法，vs2015无法编译

**Comment by sniper00** [comment]
你只是想尝试的话，可以加qq群，我给你发个编译好的

**Comment by liyqxtu** [comment]
我还是想把你的这个东西改成可以在vs2015上也能跑的版本，就功能而言，c++17能做的事情，C++11都能做。vs2022实在是太扯淡了，二三十个G的空间，而且也不支持win7

**Comment by sniper00** [comment]
你可以试试装vs2019 并且只C++开发组件，应该几个G

**Comment by liyqxtu** [comment]
另外，这个客户端是Unity2018的哪个版本呀？我的笔记本配置不高，也就只能跑一跑vs2015+unity4，用U3D 4.x打开后，系统奔溃了

**Comment by liyqxtu** [comment]
大佬的微信是多少？加一下微信，一起交流一下。
或者 加我的微信也行，我的博客地址  https://liyqs.gitee.io
上面有我的微信

**Comment by liyqxtu** [comment]
大佬，用最新的代码编译了，还是报错呀
# moon\moon.exe main_hub.lua 10000 node.json                                                                       
2023-04-10 12:38:39.196 | 4328      | INFO  | INIT with 4 workers.                                                 
2023-04-10 12:38:39.197 | 2984      | INFO  | WORKER-1 START                                                       
2023-04-10 12:38:39.198 | 4480      | INFO  | WORKER-2 START                                                       
2023-04-10 12:38:39.199 | 4076      | INFO  | WORKER-3 START                                                       
2023-04-10 12:38:39.200 | 1928      | INFO  | WORKER-4 START                                                       
2023-04-10 12:38:39.201 | :01000001 | INFO  | [WORKER 1] new service [bootstrap]                                   
2023-04-10 12:38:39.330 | 2984      | ERROR | new_service lua_error:                                               
moon/lualib/moon.lua:111: moon/lualib/moon.lua:186: bad argument #3 to '_newservice' (table expected, got no value)
stack traceback:                                                                                                   
        [C]: in upvalue '_newservice'                                                                              
        moon/lualib/moon.lua:186: in function 'mooncore.new_service'                                               
        main_hub.lua:74: in local 'fn'                                                                             
        moon/lualib/moon.lua:254: in upvalue 'invoke'                                                              
        moon/lualib/moon.lua:261: in function <moon/lualib/moon.lua:259>                                           
stack traceback:                                                                                                   
        [C]: in function 'error'                                                                                   
        moon/lualib/moon.lua:111: in upvalue 'coresume'                                                            
        moon/lualib/moon.lua:288: in function 'mooncore.async'                                                     
        main_hub.lua:67: in main chunk                                                                             
        [C]: in ?. (lua_service.cpp:134)                                                                           
2023-04-10 12:38:39.330 | :01000001 | INFO  | [WORKER 1] destroy service [bootstrap]                               
2023-04-10 12:38:39.340 | 1928      | INFO  | WORKER-4 STOP                                                        
2023-04-10 12:38:39.341 | 4076      | INFO  | WORKER-3 STOP                                                        
2023-04-10 12:38:39.341 | 4480      | INFO  | WORKER-2 STOP                                                        
2023-04-10 12:38:39.342 | 2984      | INFO  | WORKER-1 STOP                                                        
2023-04-10 12:38:39.342 | 4328      | INFO  | STOP

**Comment by sniper00** [comment]
> 大佬，用最新的代码编译了，还是报错呀
> 
> # moon\moon.exe main_hub.lua 10000 node.json
> 2023-04-10 12:38:39.196 | 4328 | INFO | INIT with 4 workers. 2023-04-10 12:38:39.197 | 2984 | INFO | WORKER-1 START 2023-04-10 12:38:39.198 | 4480 | INFO | WORKER-2 START 2023-04-10 12:38:39.199 | 4076 | INFO | WORKER-3 START 2023-04-10 12:38:39.200 | 1928 | INFO | WORKER-4 START 2023-04-10 12:38:39.201 | :01000001 | INFO | [WORKER 1] new service [bootstrap] 2023-04-10 12:38:39.330 | 2984 | ERROR | new_service lua_error: moon/lualib/moon.lua:111: moon/lualib/moon.lua:186: bad argument #3 to '_newservice' (table expected, got no value) stack traceback: [C]: in upvalue '_newservice' moon/lualib/moon.lua:186: in function 'mooncore.new_service' main_hub.lua:74: in local 'fn' moon/lualib/moon.lua:254: in upvalue 'invoke' moon/lualib/moon.lua:261: in function <moon/lualib/moon.lua:259> stack traceback: [C]: in function 'error' moon/lualib/moon.lua:111: in upvalue 'coresume' moon/lualib/moon.lua:288: in function 'mooncore.async' main_hub.lua:67: in main chunk [C]: in ?. (lua_service.cpp:134) 2023-04-10 12:38:39.330 | :01000001 | INFO | [WORKER 1] destroy service [bootstrap] 2023-04-10 12:38:39.340 | 1928 | INFO | WORKER-4 STOP 2023-04-10 12:38:39.341 | 4076 | INFO | WORKER-3 STOP 2023-04-10 12:38:39.341 | 4480 | INFO | WORKER-2 STOP 2023-04-10 12:38:39.342 | 2984 | INFO | WORKER-1 STOP 2023-04-10 12:38:39.342 | 4328 | INFO | STOP

你应该不是最新的代码，建议重新clone一份  `git clone --recursive https://github.com/sniper00/MoonDemo.git` 然后编译

**Comment by liyqxtu** [comment]
怎么有两个仓库？
https://github.com/sniper00/MoonDemo
https://github.com/sniper00/BallGame
两个是一样的么，还是说 MoonDemo 是旧的，BallGame 是最新的？
大佬的c++17代码，虽然不能用vs2015来编译，但是 mingw 还是可以编译通过的啦，我暂时是用 mingw 来编译的，后面再来研究一下怎么转成普通的c++代码

**Comment by sniper00** [comment]
> 怎么有两个仓库？ https://github.com/sniper00/MoonDemo https://github.com/sniper00/BallGame 两个是一样的么，还是说 MoonDemo 是旧的，BallGame 是最新的？ 大佬的c++17代码，虽然不能用vs2015来编译，但是 mingw 还是可以编译通过的啦，我暂时是用 mingw 来编译的，后面再来研究一下怎么转成普通的c++代码

https://github.com/sniper00/BallGame 这个应该是旧的，改了名字，Readme里面忘记改了

**Comment by liyqxtu** [comment]
这么说，我用的是最新的代码呀，可是跑起来还是报错了，是不是缺少 etc_path = "/conf.cluster" 中的 conf.cluster 导致的？

**Comment by liyqxtu** [comment]
运行 start_server.bat 中的下面这句时，报错
moon\moon.exe main_hub.lua 10000 node.json

**Comment by sniper00** [comment]
> 这么说，我用的是最新的代码呀，可是跑起来还是报错了，是不是缺少 etc_path = "/conf.cluster" 中的 conf.cluster 导致的？

是这样子 clone的吗 `git clone --recursive https://github.com/sniper00/MoonDemo.git` . 先不要用moon 里面的 release, 最近有些改动。

**Comment by liyqxtu** [comment]
重新下了一份，现在可以跑起来了

**Comment by liyqxtu** [comment]
谢谢大佬，大佬的交流群是啥，我加一下

**Comment by sniper00** [comment]
> 谢谢大佬，大佬的交流群是啥，我加一下

543833695

**Comment by liyqxtu** [comment]
加你了，这是微信号吧？

**Comment by liyqxtu** [comment]
加你了，这是微信号吧？

**Comment by sniper00** [comment]
> 加你了，这是微信号吧？

QQ群

**Comment by liyqxtu** [comment]
客户端是Unity2018的哪个版本呀？

**Comment by sniper00** [comment]
> 客户端是Unity2018的哪个版本呀？

2018 最新版本吧， 或者你试试 2020版本

**Comment by liyqxtu** [comment]
local co = coroutine.create(
function ()
	print(coroutine.running())
end)
coroutine.resume(co)
结果：thread: 00000000002F2998	false

大佬，这个协程不好理解呀，为什么print打印的结果是false？

**Comment by sniper00** [comment]
> local co = coroutine.create( function () print(coroutine.running()) end) coroutine.resume(co) 结果：thread: 00000000002F2998 false
> 
> 大佬，这个协程不好理解呀，为什么print打印的结果是false？

coroutine.resume (co [, val1, ···])
Starts or continues the execution of coroutine co. The first time you resume a coroutine, it starts running its body. The values val1, ... are passed as the arguments to the body function. If the coroutine has yielded, resume restarts it; the values val1, ... are passed as the results from the yield.

If the coroutine runs without any errors, resume returns true plus any values passed to yield (when the coroutine yields) or any values returned by the body function (when the coroutine terminates). If there is any error, resume returns false plus the error message.
