### ISSUE TITLE
关于moon+cocos creator的实现

### ISSUE THREAD

**Issue by crazyDon** [sniper00/BallGame#4]
大佬有没有cocos creator的demo可以学习，没有的话我这边自己写一个咯~

**Comment by sniper00** [comment]
> 大佬有没有cocos creator的demo可以学习，没有的话我这边自己写一个咯~

暂时没有cocos creator 版，你可以写一个，把现有gate 服务，换成websocket 协议应该就可以了

**Comment by crazyDon** [comment]
好的，谢谢大佬
